(function(){
'use strict';
const D=window.InterviewOSData||{topics:[],domains:[],projects:[],mockQuestions:[],cheatsheets:[],sources:[]};
const Store=window.InterviewStore;
const Sch=window.InterviewScheduler;
const Sims=window.InterviewSimulations||{};
const Diag=window.InterviewDiagrams||{render:()=>''};
let state=Store?Store.load():{settings:{mode:'long',motion:true,targetDate:''},topics:{},cards:{},mock:{history:[]},notes:{},stats:{}};
let ui={activeLab:'harness',reviewIndex:0,reviewRevealed:false,confidence:0,mockIndex:0,mockMode:'rapid',mockStart:0,mockRevealed:false};

const NAV=[['dashboard','⌂','Today'],['roadmap','◫','Roadmap'],['labs','⌁','Labs'],['review','↻','Review'],['mock','◉','Mock'],['projects','⬡','Projects'],['cheats','≡','Cheats'],['sources','◎','Sources']];
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const topicBy=id=>D.topics.find(t=>t.id===id);
const domainBy=id=>D.domains.find(d=>d.id===id)||{title:id,icon:'•'};
function save(){if(Store)state=Store.save(state); updateProgressBadge();}
function tstate(id){return state.topics[id]||(state.topics[id]={lesson:0,quiz:0,cards:0,explanation:0,lastStudied:0});}
function pct(v){return Math.round(clamp(Number(v)||0,0,1)*100);}
function mastery(id){return Sch?Sch.topicMastery(tstate(id)):0;}
function list(items){return (items||[]).length?`<ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p class="faint tiny">No special note for this topic.</p>';}
function badge(text,cls=''){return `<span class="badge ${cls}">${esc(text)}</span>`;}
function meter(v){return `<div class="progress"><span style="width:${clamp(v,0,100)}%"></span></div>`;}
function pageHead(k,title,desc,extra=''){return `<div class="page-head"><div><div class="eyebrow">${esc(k)}</div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div>${extra}</div>`;}
function parseRoute(hash){const parts=String(hash||'#/dashboard').replace(/^#\/?/,'').split('/').filter(Boolean);const p=parts[0]||'dashboard';return p==='topic'?{page:'topic',id:parts[1]||''}:{page:p};}

function prepareCards(){
  D.topics.forEach(t=>{(t.cards||[]).forEach((c,i)=>{const id=`${t.id}:${i}`;if(!state.cards[id])state.cards[id]={id,topicId:t.id,index:i,repetitions:0,intervalMs:0,ease:2.3,dueAt:0,lastRating:null};});});
}
prepareCards();

function totalMastery(){return D.topics.length?Math.round(D.topics.reduce((s,t)=>s+mastery(t.id),0)/D.topics.length):0;}
function dueCards(){const now=Date.now();return Object.values(state.cards).filter(c=>Sch&&typeof Sch.isDue==='function'?Sch.isDue(c,now):Number(c.dueAt)>0&&c.dueAt<=now);}
function updateProgressBadge(){if(typeof document==='undefined')return;const el=document.getElementById('sidebar-progress');if(el)el.textContent=`${totalMastery()}% mastered • ${dueCards().length} due`;}

function renderDashboard(){
  const q=Sch?Sch.buildStudyQueue(D,state,Date.now()):[];
  const dom=Sch?Sch.domainMastery(D,state):{};
  const learned=D.topics.filter(t=>mastery(t.id)>=70).length;
  const scheduled=dueCards();
  const priority=(D.priorityPath||[]).map(topicBy).filter(Boolean);
  const recent=D.topics.filter(t=>(state.topics[t.id]||{}).lastStudied).sort((a,b)=>state.topics[b.id].lastStudied-state.topics[a.id].lastStudied);
  const next=(recent.find(t=>mastery(t.id)<100)||q[0]||priority[0]||D.topics[0]||{});
  const phases=(D.curriculumPhases||[]).slice(0,4);
  const weak=q.filter(x=>x.mastery<70).slice(0,5);
  const priorityPreview=(priority.length?priority:q.map(x=>topicBy(x.id)).filter(Boolean)).slice(0,5);
  return `${pageHead('Engineering Atlas','Your engineering knowledge map','Follow prerequisites, retrieve before rereading, and turn each concept into an explanation or system decision.')}
  <section class="hero learning-hero"><div class="eyebrow">CONTINUE LEARNING</div><h1>${esc(next.title||'Start with Python foundations')}</h1><p>${esc(next.id?`${domainBy(next.domain).title} • ${mastery(next.id)}% mastery. Continue from the strongest next step in your current path.`:'Begin with the first curriculum phase and build toward senior systems architecture.')}</p><div class="learning-loop" aria-label="Learning loop">Learn → Explain → Visualize → Recall → Apply → Interview → Review</div><div class="hero-actions"><a class="btn primary" href="#/topic/${esc(next.id||'python-objects-names')}">${recent.length?'Continue lesson':'Begin the atlas'} →</a><a class="btn secondary" href="#/roadmap">Open Master Curriculum</a><a class="btn ghost" href="#/review">${scheduled.length?`Review ${scheduled.length} due`:'Start recall practice'}</a></div></section>
  <div class="grid four"><div class="card metric"><strong>${totalMastery()}%</strong><span>Overall mastery</span><small>lesson + quiz + recall + explanation</small></div><div class="card metric"><strong>${learned}/${D.topics.length}</strong><span>Lessons ready</span><small>topics at 70% mastery or higher</small></div><div class="card metric"><strong>${scheduled.length}</strong><span>Review Due</span><small>${scheduled.length} scheduled cards • unseen cards stay new</small></div><div class="card metric"><strong>${state.mock.history.length||0}</strong><span>Interview answers</span><small>attempts scored and reflected on</small></div></div>
  <div class="grid two dashboard-split"><section class="card"><div class="section-title"><h2>Priority Interview Path</h2><a href="#/roadmap">View all ${priority.length||q.length} →</a></div>${priorityPreview.map((x,i)=>`<a class="study-item" href="#/topic/${x.id}"><div class="priority-dot">${String(i+1).padStart(2,'0')}</div><div><h4>${esc(x.title)}</h4><p>${esc(domainBy(x.domain).title)} • P${x.priority}</p></div><div class="mastery-ring" style="--pct:${mastery(x.id)}%"><span>${mastery(x.id)}</span></div></a>`).join('')}</section>
  <section class="card"><div class="section-title"><h2>Master Curriculum</h2><a href="#/roadmap">Open roadmap →</a></div>${phases.length?phases.map((p,i)=>{const ts=(p.topics||[]).map(topicBy).filter(Boolean);const value=ts.length?Math.round(ts.reduce((sum,t)=>sum+mastery(t.id),0)/ts.length):0;return `<a class="study-item" href="#/roadmap"><div class="priority-dot">${i+1}</div><div><h4>${esc(p.title)}</h4><p>${ts.length} lessons • ${esc(p.goal)}</p></div><strong class="tiny">${value}%</strong></a>`;}).join(''):'<p class="muted">The curriculum builds from foundations to system architecture.</p>'}</section></div>
  <div class="grid three dashboard-split"><section class="card"><div class="section-title"><h2>Review Due</h2><span>${scheduled.length} scheduled cards</span></div><p>${scheduled.length?'Retrieve these concepts before rereading them.':'Nothing is overdue. Choose a new recall set when you are ready.'}</p><a class="btn secondary" href="#/review">${scheduled.length?'Review now':'Practice new cards'} →</a></section>
  <section class="card"><div class="section-title"><h2>Weak Areas</h2><span>adaptive</span></div>${weak.slice(0,3).map(x=>`<a class="compact-link" href="#/topic/${x.id}"><span>${esc(x.title)}</span><strong>${x.mastery}%</strong></a>`).join('')||'<p class="muted">Study a lesson to begin measuring weak areas.</p>'}</section>
  <section class="card"><div class="section-title"><h2>Recent Topics</h2><span>resume context</span></div>${recent.slice(0,3).map(t=>`<a class="compact-link" href="#/topic/${t.id}"><span>${esc(t.title)}</span><strong>${mastery(t.id)}%</strong></a>`).join('')||'<p class="muted">Your studied topics will appear here.</p>'}</section></div>
  <div class="grid three dashboard-split"><a class="card launch-card" href="#/projects"><div class="eyebrow">PROJECT ARCHITECTURES</div><h2>Trace production systems</h2><p>Walk through sanitized video AI, recognition, RAG, inference, and durable pipeline decisions.</p><span>Explore ${D.projects.length} cases →</span></a><a class="card launch-card" href="#/labs"><div class="eyebrow">INTERACTIVE LABS</div><h2>Change the system</h2><p>Predict a result, move a control, then explain the latency, capacity, or reliability trade-off.</p><span>Open laboratories →</span></a><a class="card launch-card" href="#/mock"><div class="eyebrow">MOCK INTERVIEW</div><h2>Answer under pressure</h2><p>Practice concise technical answers, system design, incidents, and architecture leadership.</p><span>Start an interview →</span></a></div>
  <div class="section-title"><h2>Study cycle</h2><span>active knowledge, not passive pages</span></div><div class="study-cycle"><div><b>01</b><strong>Learn</strong><span>Build the mental model.</span></div><div><b>02</b><strong>Explain</strong><span>Use your own words.</span></div><div><b>03</b><strong>Visualize</strong><span>Follow data and state.</span></div><div><b>04</b><strong>Recall</strong><span>Answer before reveal.</span></div><div><b>05</b><strong>Apply</strong><span>Change a lab or design.</span></div><div><b>06</b><strong>Interview</strong><span>Say the trade-off aloud.</span></div><div><b>07</b><strong>Review</strong><span>Return at the right time.</span></div></div>
  <div class="grid two dashboard-split"><section class="card"><div class="section-title"><h2>Domain heatmap</h2><span>mastery by system</span></div>${D.domains.map(d=>`<div class="domain-row"><div class="domain-label"><span>${d.icon} ${esc(d.title)}</span><strong>${(dom[d.id]||{}).value||0}%</strong></div>${meter((dom[d.id]||{}).value||0)}</div>`).join('')}</section><section class="card"><div class="section-title"><h2>Architecture transfer</h2><span>connect concept to evidence</span></div><div class="callout green"><strong>Video systems:</strong> ingestion → queues → workers/GPU → state and artifacts → events.</div><div class="callout" style="margin-top:8px"><strong>Recognition:</strong> detection → alignment/tracking → embedding or OCR → temporal decision.</div><div class="callout amber" style="margin-top:8px"><strong>AI systems:</strong> retrieval/model/tool stages need explicit latency, safety, evaluation, and fallback boundaries.</div></section></div>`;
}

function renderRoadmap(){
 const reqs=D.requirements||[];
 const coverage=reqs.length?`<section class="card" style="margin-bottom:18px"><div class="section-title"><h2>Requirement coverage — priority role</h2><span>strengths, gaps and linked lessons</span></div><div class="grid two">${reqs.map(r=>{const ids=r.topics||[];const avg=ids.length?Math.round(ids.reduce((sum,id)=>sum+mastery(id),0)/ids.length):0;const cls=/hands-on|strong/i.test(r.status)?'used':/gap|growth|deepen|mixed/i.test(r.status)?'hot':'';return `<article class="card card-subtle"><div style="display:flex;justify-content:space-between;gap:8px;align-items:start"><h3>${esc(r.skill)}</h3>${badge(r.status,cls)}</div><p>${esc(r.evidence)}</p><div class="tiny muted" style="margin-bottom:5px">Mapped mastery ${avg}%</div>${meter(avg)}<div class="tag-row" style="margin-top:8px">${ids.slice(0,5).map(id=>{const t=topicBy(id);return t?`<a class="tag" href="#/topic/${id}">${esc(t.title)}</a>`:''}).join('')}</div></article>`;}).join('')}</div></section>`:'';
 const priority=(D.priorityPath||[]).map(topicBy).filter(Boolean);
 const priorityHtml=priority.length?`<section class="card path-section"><div class="section-title"><h2>Priority Interview Path</h2><span>${priority.length} ordered topics • study this first</span></div><p class="muted">This path deliberately front-loads production AI runtime, Python async, database/messaging and scalability. Finish it in order once; after that use the adaptive queue.</p><div class="path-grid">${priority.map((t,i)=>`<a class="path-step" href="#/topic/${t.id}"><span class="path-num">${String(i+1).padStart(2,'0')}</span><span><strong>${esc(t.title)}</strong><small>${esc(domainBy(t.domain).title)} • ${mastery(t.id)}%</small></span></a>`).join('')}</div></section>`:'';
 const phases=(D.curriculumPhases||[]).map((p,i)=>{const ts=(p.topics||[]).map(topicBy).filter(Boolean);const avg=ts.length?Math.round(ts.reduce((a,t)=>a+mastery(t.id),0)/ts.length):0;return `<section class="card phase-card"><div class="phase-index">${i+1}</div><div><div class="eyebrow">LONG-TERM PHASE</div><h2>${esc(p.title)}</h2><p>${esc(p.goal)}</p><div class="tiny muted">${ts.length} mapped topics • ${avg}% mastery</div>${meter(avg)}<div class="tag-row" style="margin-top:9px">${ts.slice(0,8).map(t=>`<a class="tag" href="#/topic/${t.id}">${esc(t.title)}</a>`).join('')}</div></div></section>`;}).join('');
 return `${pageHead('Curriculum','Progressive engineering roadmap','Start with the priority sequence, then move through foundations → AI/ML → vision → distributed systems → senior architecture. Every lesson remains available in the domain library.')}${coverage}${priorityHtml}<div class="section-title"><h2>Long-term mastery path</h2><span>foundations first, advanced architecture later</span></div><div class="phase-list">${phases}</div><div class="section-title"><h2>Full topic library</h2><span>${D.topics.length} lessons by domain</span></div><input class="search-input" data-topic-search placeholder="Search topics: asyncio, Postgres, Kafka, YOLO, cosine, RAG…" aria-label="Search topics">${D.domains.map(d=>{const ts=D.topics.filter(t=>t.domain===d.id).sort((a,b)=>b.priority-a.priority||a.title.localeCompare(b.title));const avg=ts.length?Math.round(ts.reduce((sum,t)=>sum+mastery(t.id),0)/ts.length):0;return `<section class="domain-block card"><div class="domain-head"><div class="domain-icon">${d.icon}</div><div style="flex:1"><h2 style="font-size:15px;margin:0">${esc(d.title)}</h2><div class="tiny muted">${ts.length} topics • ${avg}% mastery</div>${meter(avg)}</div></div><div class="topic-grid">${ts.map(t=>`<a href="#/topic/${t.id}" class="topic-tile" data-topic-search-item="${esc((t.title+' '+domainBy(t.domain).title+' '+(t.terms||[]).join(' ')).toLowerCase())}"><div><h4>${esc(t.title)}</h4><div class="tag-row">${badge('P'+t.priority,t.priority>=5?'hot':'')}${t.usedByYou&&t.usedByYou.length?badge('Used by you','used'):''}</div></div><div class="mastery-ring" style="--pct:${mastery(t.id)}%"><span>${mastery(t.id)}</span></div></a>`).join('')}</div></section>`;}).join('')}`;
}

function renderTopic(id){
 const t=topicBy(id); if(!t)return `<div class="card"><h2>Topic not found</h2><a class="btn" href="#/roadmap">Back to roadmap</a></div>`;
 const st=tstate(id); const q=t.quiz&&t.quiz[0];
 const prereq=(t.prerequisites||[]).map(topicBy).filter(Boolean),next=(t.nextTopics||[]).map(topicBy).filter(Boolean);
 const terms=(t.terms||[]),functions=(t.functions||[]);
 return `${pageHead(domainBy(t.domain).title,t.title,`Priority P${t.priority} • mastery ${mastery(id)}%`,`<a class="btn secondary" href="#/roadmap">← Roadmap</a>`)}
 ${prereq.length?`<section class="callout"><strong>Build on first:</strong> ${prereq.map(x=>`<a class="tag" href="#/topic/${x.id}">${esc(x.title)}</a>`).join(' ')}</section>`:''}
 <div class="lesson-layout"><div>
 <section class="recall-box"><div class="eyebrow">Recall first — do not peek yet</div><h2>Explain ${esc(t.title)} aloud in 30–60 seconds.</h2><p class="muted">Say: what it is → why it exists → important terms/functions → failure mode → trade-off → where you used something similar.</p><div class="actions"><button class="btn primary" data-action="reveal-lesson" data-topic="${t.id}">I attempted it — reveal lesson</button>${badge('Retrieval practice','research')}</div><div class="answer-panel" id="lesson-answer-${t.id}"><div class="lesson-section card"><h2>Simple intuition</h2><p>${esc(t.intuition)}</p></div><div class="lesson-section card"><h2>Technical interview language</h2><p>${esc(t.technical)}</p></div></div></section>
 <section class="lesson-section card"><div class="section-title"><h2>Visual model</h2><span>follow the data</span></div><div class="diagram-wrap">${Diag.render(t.diagram||'generic')}</div></section>
 ${(terms.length||functions.length)?`<div class="grid two"><section class="lesson-section card"><h2>Terms you must be able to define</h2><div class="term-cloud">${terms.map(x=>`<span class="term-pill">${esc(x)}</span>`).join('')}</div></section><section class="lesson-section card"><h2>Functions / APIs / commands to recognize</h2>${functions.length?`<div class="function-list">${functions.map(x=>`<code>${esc(x)}</code>`).join('')}</div>`:'<p class="muted">Conceptual topic—focus on the interface and data flow.</p>'}</section></div>`:''}
 ${t.code?`<section class="lesson-section card"><div class="section-title"><h2>${esc(t.codeTitle||'Concrete example')}</h2><span>read it, then explain each line</span></div><pre class="code-block"><code>${esc(t.code)}</code></pre></section>`:''}
 <div class="grid two"><section class="lesson-section card"><h2>What to remember</h2>${list(t.keyPoints)}</section><section class="lesson-section card"><h2>Where you used it</h2>${(t.usedByYou||[]).map(x=>`<div class="callout green" style="margin:7px 0">${esc(x)}</div>`).join('')||'<p class="muted">Use an adjacent project example or say explicitly that this is study knowledge.</p>'}</section></div>
 <div class="grid two"><section class="lesson-section card"><h2>Trade-offs</h2>${list(t.tradeoffs)}</section><section class="lesson-section card"><h2>Failure modes</h2>${list(t.failureModes)}</section></div>
 <div class="grid two"><section class="lesson-section card"><h2>Scalability</h2>${list(t.scaling)}</section><section class="lesson-section card"><h2>Security / reliability</h2>${list(t.security)}</section></div>
 <section class="lesson-section card"><div class="eyebrow">Interview answer</div><h2>How to say it clearly</h2><div class="interview-answer">${esc(t.interviewAnswer)}</div><div class="divider"></div><div class="eyebrow">Deep follow-up</div><p>${esc(t.deepDive||'Connect the concept to concrete metrics, failure handling and trade-offs.')}</p></section>
 <section class="lesson-section card"><h2>Common traps</h2>${list(t.traps)}</section>
 <section class="lesson-section card"><div class="eyebrow">Active recall checkpoint</div><h2>${esc((q||{}).q||'Choose the best answer')}</h2><div>${(q&&q.options||[]).map((o,i)=>`<button class="quiz-option" data-action="answer-quiz" data-topic="${t.id}" data-index="${i}">${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('')}</div><div id="quiz-feedback-${t.id}" class="tiny muted"></div></section>
 <section class="lesson-section card"><div class="eyebrow">Feynman transfer</div><h2>Explain it in your own words</h2><p>Write as if explaining to a CTO who cares about impact, reliability and cost. Writing forces retrieval and connection—not recognition.</p><textarea class="self-explain" id="self-${t.id}" placeholder="My explanation…">${esc(state.notes['topic:'+t.id]||'')}</textarea><div class="actions"><button class="btn primary" data-action="save-explanation" data-topic="${t.id}">Save explanation</button><button class="btn secondary" data-action="complete-topic" data-topic="${t.id}">Mark lesson studied</button></div></section>
 ${next.length?`<section class="lesson-section card"><div class="eyebrow">Continue the chain</div><h2>Next concepts</h2><div class="tag-row">${next.map(x=>`<a class="tag" href="#/topic/${x.id}">${esc(x.title)} →</a>`).join('')}</div></section>`:''}
 </div><aside class="lesson-nav card"><div class="eyebrow">Mastery</div><strong style="font-size:32px">${mastery(t.id)}%</strong>${meter(mastery(t.id))}<div class="divider"></div><div class="tiny muted">Lesson</div>${meter(pct(st.lesson))}<div class="tiny muted" style="margin-top:8px">Quiz</div>${meter(pct(st.quiz))}<div class="tiny muted" style="margin-top:8px">Review cards</div>${meter(pct(st.cards))}<div class="tiny muted" style="margin-top:8px">Self-explanation</div>${meter(pct(st.explanation))}<div class="divider"></div>${terms.length?`<div class="tiny muted">Key vocabulary</div><div class="tag-row" style="margin-top:6px">${terms.slice(0,7).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><div class="divider"></div>`:''}<a class="btn secondary" style="display:block;text-align:center" href="#/review">Review flashcards</a></aside></div>`;
}

function labTabs(){const tabs=[['harness','Agent Harness'],['python','Python Async'],['db','DB Load'],['messaging','Messaging'],['capacity','Capacity'],['inference','GPU / Triton'],['rag','RAG'],['cosine','Cosine'],['yolo','YOLO / NMS'],['scale','Scaling'],['failure','Failure Lab']];return `<div class="lab-tabs">${tabs.map(([id,n])=>`<button class="btn lab-tab ${ui.activeLab===id?'active':''}" data-action="lab-tab" data-lab="${id}">${n}</button>`).join('')}</div>`;}
function simMetrics(obj,keys){return `<div class="sim-metrics">${keys.map(([k,l,s=''])=>`<div class="sim-metric"><strong>${esc(obj[k])}${s}</strong><small>${esc(l)}</small></div>`).join('')}</div><div class="sim-note">${esc(obj.label||'Synthetic simulation — not a benchmark')}</div>`;}
function range(name,label,min,max,step,val,suffix=''){return `<div class="control-group"><label>${esc(label)} <span id="v-${name}">${esc(val)}${suffix}</span></label><input type="range" min="${min}" max="${max}" step="${step}" value="${val}" data-lab-input="${name}" data-suffix="${suffix}"></div>`;}
function sw(name,label,checked){return `<label class="switch-row"><span>${esc(label)}</span><input class="switch" type="checkbox" data-lab-input="${name}" ${checked?'checked':''}></label>`;}
function renderLabBody(){
 const L=ui.activeLab;
 if(L==='harness'){const c=ui.harness||{routing:true,rag:true,memory:false,retries:true,verifier:false,guardrails:true};const r=Sims.HarnessSim.run(c);return `<div class="lab-layout"><div class="card lab-controls"><h3>Build the AI runtime harness</h3>${sw('routing','Model routing',c.routing)}${sw('rag','RAG context',c.rag)}${sw('memory','Long-term memory',c.memory)}${sw('retries','Retry / repair loop',c.retries)}${sw('verifier','Verifier step',c.verifier)}${sw('guardrails','Policy guardrails',c.guardrails)}<div class="callout amber">Predict first: which switch improves success most, and which one is safest to remove for a low-risk task?</div></div><div class="card"><h3>Reliability vs latency / cost</h3><div class="diagram-wrap">${Diag.render('harness')}</div>${simMetrics(r,[['successPct','Task success','%'],['latencyMs','Latency','ms'],['costUnits','Cost units'],['riskScore','Risk score']])}<div class="callout">Senior answer: optimize the <em>critical path</em>. Parallelize independent context/tool work, route simple requests cheaply, cache stable context, and reserve verifier/retry layers for risk tiers that justify them.</div></div></div>`;}
 if(L==='python'){const c=ui.async||{rps:250,ioMs:100,limit:40,cpuMs:2};const r=Sims.AsyncSim.run(c);return `<div class="lab-layout"><div class="card lab-controls"><h3>Event loop pressure</h3>${range('rps','Requests/sec',20,1200,10,c.rps)}${range('ioMs','Awaited I/O latency',5,500,5,c.ioMs,'ms')}${range('limit','Dependency concurrency limit',2,200,2,c.limit)}${range('cpuMs','Blocking CPU per request',0,30,1,c.cpuMs,'ms')}<div class="callout amber">Before moving CPU ms, predict what happens to every concurrent request sharing this event loop.</div></div><div class="card"><h3>Async is not unlimited parallelism</h3><div class="diagram-wrap">${Diag.render('queue')}</div>${simMetrics(r,[['inFlight','Avg in flight'],['ioCapacity','I/O capacity','/s'],['eventLoopPressurePct','Loop pressure','%'],['p95Ms','Synthetic p95','ms']])}<div class="callout ${r.status==='overloaded'?'red':r.status==='warm'?'amber':'green'}"><strong>${r.status.toUpperCase()}:</strong> I/O waiting can overlap. CPU/synchronous blocking stalls the loop; unbounded concurrency only moves the bottleneck to pools, GPU, memory or downstream services.</div></div></div>`;}
 if(L==='db'){const c=ui.db||{rows:1000000,selectivity:.01,index:false,cacheHit:.2,pool:60,replicas:0,readRatio:.8};const r=Sims.DbSim.run(c);return `<div class="lab-layout"><div class="card lab-controls"><h3>Reduce database load</h3>${range('rows','Table rows',100000,10000000,100000,c.rows)}${range('selectivity','Rows matched ratio',.001,.2,.001,c.selectivity)}${sw('index','Selective index',c.index)}${range('cacheHit','Cache hit ratio',0,.95,.05,c.cacheHit)}${range('pool','Connection pool / replica',5,200,5,c.pool)}${range('replicas','Read replicas',0,4,1,c.replicas)}</div><div class="card"><h3>Query path</h3><div class="diagram-wrap">${Diag.render('db')}</div>${simMetrics(r,[['scannedRows','Rows scanned'],['primaryLoad','Primary load'],['poolPressure','Pool penalty'],['cacheMissPct','Cache miss','%']])}<div class="callout green"><strong>Order of attack:</strong> measure → query shape → EXPLAIN ANALYZE → index → remove N+1 / over-fetching → cache hot reads → bound pools → replica/partition only when justified. ${esc(r.recommendation)}</div></div></div>`;}
 if(L==='messaging'){const c=ui.msg||{broker:'kafka',rate:1200,consumers:4,consumerRate:250};const r=Sims.MessagingSim.run(c);return `<div class="lab-layout"><div class="card lab-controls"><h3>Traffic & broker</h3><div class="control-group"><label>Broker</label><select data-lab-input="broker"><option value="zset" ${c.broker==='zset'?'selected':''}>Redis ZSET</option><option value="streams" ${c.broker==='streams'?'selected':''}>Redis Streams</option><option value="rabbit" ${c.broker==='rabbit'?'selected':''}>RabbitMQ</option><option value="kafka" ${c.broker==='kafka'?'selected':''}>Kafka</option><option value="mqtt" ${c.broker==='mqtt'?'selected':''}>MQTT</option></select></div>${range('rate','Producer msg/s',100,5000,100,c.rate)}${range('consumers','Consumers',1,20,1,c.consumers)}${range('consumerRate','Each consumer msg/s',50,1000,50,c.consumerRate)}<div class="callout amber">Choose by semantics, not popularity: replay? routing? per-key ordering? device pub/sub? task execution?</div></div><div class="card"><h3>What happens?</h3><div class="diagram-wrap">${Diag.render('queue')}</div>${simMetrics(r,[['capacity','Capacity','/s'],['backlog','Backlog growth','/s'],['utilizationPct','Consumer utilization','%'],['replay','Replay']])}<div class="grid two" style="margin-top:12px"><div class="callout"><strong>Ordering:</strong> ${esc(r.ordering)}</div><div class="callout"><strong>Recovery:</strong> ${esc(r.ack)}</div></div></div></div>`;}
 if(L==='capacity'){const c=ui.capacity||{rps:800,latencyMs:180,replicas:3,capacityPerReplica:350,headroom:.3};const r=Sims.CapacitySim.run(c);return `<div class="lab-layout"><div class="card lab-controls"><h3>Back-of-envelope sizing</h3>${range('rps','Peak RPS',50,10000,50,c.rps)}${range('latencyMs','Average response time',20,1500,20,c.latencyMs,'ms')}${range('replicas','Current replicas',1,30,1,c.replicas)}${range('capacityPerReplica','Measured replica capacity',50,1000,25,c.capacityPerReplica,'/s')}${range('headroom','Desired headroom',0,.6,.05,c.headroom)}</div><div class="card"><h3>Capacity model</h3><div class="diagram-wrap">${Diag.render('scale')}</div>${simMetrics(r,[['inFlight','Little’s Law in-flight'],['capacity','Total capacity','/s'],['utilizationPct','Utilization','%'],['recommendedReplicas','Recommended replicas']])}<div class="callout green">Interview habit: estimate traffic × object sizes × retention × latency/concurrency first. Your exact number can be rough; your assumptions and bottleneck reasoning must be explicit.</div></div></div>`;}
 if(L==='inference'){const c=ui.inf||{batch:1,concurrency:4,instances:1,quantization:false};const r=Sims.InferenceSim.run(c);return `<div class="lab-layout"><div class="card lab-controls"><h3>Triton / GPU tuning</h3>${range('batch','Batch size',1,32,1,c.batch)}${range('concurrency','Concurrency',1,64,1,c.concurrency)}${range('instances','Model instances',1,4,1,c.instances)}${sw('quantization','Quantized model',c.quantization)}</div><div class="card"><h3>Latency vs throughput</h3><div class="diagram-wrap">${Diag.render('gpu')}</div>${simMetrics(r,[['throughput','Throughput','/s'],['queueMs','Queue time','ms'],['p95Ms','Synthetic p95','ms'],['gpuMemoryGB','GPU memory','GB']])}<div class="callout green">ANPR anchor: batching recognition crops can amortize inference overhead and improve GPU utilization, but batch wait must stay inside the real-time latency budget. Measure queue, preprocess, H2D, compute and postprocess separately.</div></div></div>`;}
 if(L==='rag'){const c=ui.rag||{topK:5,chunk:700,rerank:true,queryRewrite:true};const r=Sims.RagSim.run(c);return `<div class="lab-layout"><div class="card lab-controls"><h3>Retrieval knobs</h3>${range('topK','Top K',1,20,1,c.topK)}${range('chunk','Chunk tokens',150,1800,50,c.chunk)}${sw('rerank','Reranker',c.rerank)}${sw('queryRewrite','Query rewrite',c.queryRewrite)}</div><div class="card"><h3>Grounding quality</h3><div class="diagram-wrap">${Diag.render('harness')}</div>${simMetrics(r,[['recallPct','Retrieval recall','%'],['precisionPct','Context precision','%'],['contextTokens','Context tokens'],['latencyMs','Retrieval latency','ms']])}<div class="callout">Evaluate retrieval recall/precision separately from answer faithfulness. Citation does not magically eliminate hallucination—the cited evidence must actually support the claim.</div></div></div>`;}
 if(L==='cosine'){const c=ui.cosine||{ax:1,ay:.5,bx:.8,by:.7};const r=Sims.CosineSim.run(c);return `<div class="lab-layout"><div class="card lab-controls"><h3>Move two embedding vectors</h3>${range('ax','Vector A · x',-2,2,.1,c.ax)}${range('ay','Vector A · y',-2,2,.1,c.ay)}${range('bx','Vector B · x',-2,2,.1,c.bx)}${range('by','Vector B · y',-2,2,.1,c.by)}<div class="callout amber">Now multiply A by 2 without changing its direction. Predict cosine before trying it.</div></div><div class="card"><h3>Direction, not magnitude</h3><div class="vector-stage"><div><strong>A</strong> (${esc(c.ax)}, ${esc(c.ay)})</div><div><strong>B</strong> (${esc(c.bx)}, ${esc(c.by)})</div></div>${simMetrics(r,[['dot','Dot product'],['cosine','Cosine'],['angleDeg','Angle','°'],['match','Similarity']])}<div class="callout green">For L2-normalized ArcFace embeddings, inner product equals cosine similarity. Top-k retrieves candidates; a calibrated threshold decides whether a match is acceptable.</div></div></div>`;}
 if(L==='yolo'){const c=ui.yolo||{confidence:.4,iou:.5,crowding:.4};const r=Sims.YoloSim.run(c);return `<div class="lab-layout"><div class="card lab-controls"><h3>Detector post-processing</h3>${range('confidence','Confidence threshold',.05,.95,.05,c.confidence)}${range('iou','NMS IoU threshold',.1,.9,.05,c.iou)}${range('crowding','Scene crowding',0,1,.1,c.crowding)}<div class="callout amber">Predict: what happens to recall when confidence rises? What happens to duplicates when NMS IoU is too permissive?</div></div><div class="card"><h3>Precision / recall trade-off</h3><div class="diagram-wrap">${Diag.render('pipeline')}</div>${simMetrics(r,[['precisionPct','Synthetic precision','%'],['recallPct','Synthetic recall','%'],['candidates','Candidates'],['kept','Kept after NMS']])}<div class="grid two"><div class="callout"><strong>Duplicate risk:</strong> ${esc(r.duplicateRisk)}%</div><div class="callout"><strong>Miss risk:</strong> ${esc(r.missRisk)}%</div></div><div class="callout green" style="margin-top:8px">ANPR/MMC lesson: debug detector recall, classification/recognition and tracker stability separately. One end-to-end accuracy number hides the failing stage.</div></div></div>`;}
 if(L==='scale'){const c=ui.scale||{rps:1200,replicas:3,cacheHit:.4,dbCapacity:550};const r=Sims.ScaleSim.run(c);return `<div class="lab-layout"><div class="card lab-controls"><h3>Turn the traffic knobs</h3>${range('rps','Requests/sec',100,5000,100,c.rps)}${range('replicas','App replicas',1,20,1,c.replicas)}${range('cacheHit','Cache hit ratio',0,.95,.05,c.cacheHit)}${range('dbCapacity','DB capacity QPS',100,2000,50,c.dbCapacity)}</div><div class="card"><h3>System pressure</h3><div class="diagram-wrap">${Diag.render('scale')}</div>${simMetrics(r,[['appUtilPct','App utilization','%'],['dbQps','DB QPS'],['dbUtilPct','DB utilization','%'],['p95Ms','Synthetic p95','ms']])}<div class="callout ${r.status==='overloaded'?'red':r.status==='warm'?'amber':'green'}"><strong>${r.status.toUpperCase()}:</strong> Adding stateless app replicas cannot fix a saturated shared database. Reduce work per request and scale the bottleneck, not the easiest tier.</div></div></div>`;}
 const scenarios=[['Redis disappears during video processing','Stop or limit producers → identify what state is durable → restore/replay/reclaim safely → reconcile progress. Then explain why ZSET needs more application logic than Streams/Kafka for acknowledgements.'],['A synchronous model SDK is called from FastAPI async def','Confirm event-loop lag → move blocking I/O to async client/thread boundary or CPU/model work to worker/process → cap concurrency → measure p95 again.'],['Postgres CPU reaches 95%','Check top queries and waits → EXPLAIN ANALYZE → indexes/query shape/N+1 → connection count/pool waits → cache hot reads → replicas only after query work.'],['An AI agent repeats a side-effecting tool','Idempotency key + durable tool-call ledger/state checkpoint + authorization. Never rely on “the LLM probably will not call twice.”'],['Kafka consumer lag keeps growing','Check partition skew, consumer processing time/errors, downstream DB/model latency and rebalances. Scale consumers only up to useful partition parallelism.'],['GPU OOM appears under burst traffic','Admission control → bounded queue/concurrency → inspect weights/KV/activations/batch memory → reduce batch/context/precision or add replicas. Separate queue wait from compute.'],['ANPR OCR becomes the slow stage','Measure detector vs recognizer latency → batch plate crops for Triton → test batch delay → keep temporal voting/dedup outside inference → watch GPU utilization and end-to-end p95.'],['Cache outage sends all traffic to DB','Rate limit/load shed → protect DB pool → temporary degraded response → restore cache gradually. Prevent stampede when cache comes back.']];return `<div class="grid two">${scenarios.map((x,i)=>`<article class="card"><div class="eyebrow">Failure ${i+1}</div><h3>${esc(x[0])}</h3><p>Before reveal, say: detect → contain → recover → prevent.</p><button class="btn secondary" data-action="toggle-failure" data-target="failure-${i}">Reveal response</button><div class="answer-panel" id="failure-${i}"><div class="callout green" style="margin-top:8px">${esc(x[1])}</div></div></article>`).join('')}</div>`;
}

function renderLab(name){const before=ui.activeLab;ui.activeLab=name||before;let html;try{html=renderLabBody();}finally{ui.activeLab=before;}return html;}
function renderLabs(){return `${pageHead('Interactive architecture','Systems labs','Change one variable, observe the system, then explain the trade-off aloud. Numbers are intentionally synthetic—not benchmarks.')}${labTabs()}<div id="lab-body">${renderLabBody()}</div>`;}

function reviewDeck(){const now=Date.now();let due=dueCards();if(!due.length)due=Object.values(state.cards).filter(c=>!c.lastReviewed).slice(0,12);return due.map(c=>{const t=topicBy(c.topicId),card=t&&t.cards&&t.cards[c.index];return card?{...c,q:card.q,a:card.a,title:t.title}:null}).filter(Boolean);}
function renderReview(){const deck=reviewDeck();if(!deck.length)return `${pageHead('Spaced retrieval','Review','No cards available yet.')}<div class="card">Open a topic to generate review material.</div>`;ui.reviewIndex=ui.reviewIndex%deck.length;const c=deck[ui.reviewIndex];return `${pageHead('Spaced retrieval','Review','Try to retrieve before revealing. Confidence helps expose the dangerous “I thought I knew it” gap.',`<span class="badge">${ui.reviewIndex+1}/${deck.length}</span>`)}<div class="review-shell"><div class="flashcard"><div class="eyebrow">${esc(c.title)}</div><div class="question">${esc(c.q)}</div><div class="confidence-row"><span class="tiny muted">Confidence before reveal:</span>${[1,2,3,4,5].map(n=>`<button class="btn ${ui.confidence===n?'primary':''}" data-action="confidence" data-value="${n}">${n}</button>`).join('')}</div><div class="actions" style="justify-content:center"><button class="btn primary" data-action="reveal-card">Reveal answer <span class="faint">[Space]</span></button></div><div class="flash-answer ${ui.reviewRevealed?'revealed':''}" id="flash-answer"><div class="divider"></div><p>${esc(c.a)}</p><div class="callout">Now say one concrete example or failure mode that was <em>not</em> printed on the card.</div></div></div><div class="rating-row ${ui.reviewRevealed?'show':''}"><button class="btn rating-btn" data-action="rate-card" data-card="${c.id}" data-rating="again">1 Again</button><button class="btn rating-btn" data-action="rate-card" data-card="${c.id}" data-rating="hard">2 Hard</button><button class="btn rating-btn" data-action="rate-card" data-card="${c.id}" data-rating="good">3 Good</button><button class="btn rating-btn" data-action="rate-card" data-card="${c.id}" data-rating="easy">4 Easy</button></div><p class="tiny muted" style="text-align:center">Sprint mode returns weak cards in minutes/hours. Long-term mode spaces successful recall over days.</p></div>`;}

function mockPool(){return D.mockQuestions.filter(q=>q.type===ui.mockMode);}
function renderMock(){const pool=mockPool();if(!pool.length)return `${pageHead('Interview transfer','Mock interview','No questions in this mode.')}<div class="card">Choose another mode.</div>`;ui.mockIndex%=pool.length;const q=pool[ui.mockIndex];return `${pageHead('Interview transfer','Mock interview','Answer aloud before opening the rubric. Treat it like the real call: structured, concrete, trade-off aware.')}
<div class="lab-tabs">${[['rapid','Rapid fire'],['system','System design'],['cto','CTO / leadership']].map(([id,l])=>`<button class="btn lab-tab ${ui.mockMode===id?'active':''}" data-action="mock-mode" data-mode="${id}">${l}</button>`).join('')}</div><article class="card mock-card"><div style="display:flex;justify-content:space-between;gap:12px"><div class="eyebrow">${esc(ui.mockMode)} • question ${ui.mockIndex+1}/${pool.length}</div><div class="timer" id="mock-timer">00:00</div></div><div class="mock-question">${esc(q.q)}</div><div class="actions"><button class="btn primary" data-action="mock-start">Start timer</button><button class="btn secondary" data-action="mock-reveal">Reveal rubric</button><button class="btn ghost" data-action="mock-next">Next →</button></div><div class="rubric ${ui.mockRevealed?'revealed':''}" id="mock-rubric"><div class="divider"></div><h3>Strong answer should cover</h3>${list(q.rubric)}<div class="callout green">Score yourself for structure, correctness, trade-offs, failure handling and a concrete project anchor—not for sounding fancy.</div><h3 style="margin-top:14px">Self-score</h3><div class="score-row">${[1,2,3,4,5].map(n=>`<button class="btn score-btn" data-action="mock-score" data-score="${n}">${n}</button>`).join('')}</div></div></article>`;}

function renderProjects(){return `${pageHead('Your evidence','Project map','Interviewers remember concrete systems. Use these anchors to turn abstract architecture answers into experienced answers.')}${D.projects.map(p=>{const tech=p.tech||p.flow||[];const gaps=p.improvements||p.upgrades||p.gaps||[];return `<article class="card project-card" style="margin-bottom:12px"><div style="display:flex;justify-content:space-between;gap:12px;align-items:start"><div><div class="eyebrow">${esc(p.role||p.badge||'Production system')}</div><h2 style="font-size:18px;margin:4px 0">${esc(p.title||p.name)}</h2><p>${esc(p.summary||p.description||'')}</p></div>${badge(p.badge||'Used by you','used')}</div><div class="tag-row">${tech.map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><div class="project-flow diagram-wrap">${Diag.render(p.diagram||'pipeline')}</div><div class="strength-grid"><div class="mini-list"><strong>What you can defend</strong>${list(p.strengths||p.proof||[])}</div><div class="mini-list"><strong>Known gaps / upgrade path</strong>${list(gaps)}${p.upgrade?`<div class="callout amber" style="margin-top:8px">${esc(p.upgrade)}</div>`:''}</div></div>${p.interviewAnchor?`<div class="callout green" style="margin-top:10px"><strong>Say this:</strong> ${esc(p.interviewAnchor)}</div>`:''}</article>`;}).join('')||'<div class="card">Project map loading from your source notes.</div>'}`;}

function renderCheats(){const glossary=D.glossary||[];return `${pageHead('Fast retrieval','Cheats + engineering glossary','Decision ladders and definitions. Try to define each term before reading its description.')}<section class="card" style="margin-bottom:14px"><div class="section-title"><h2>Glossary (${glossary.length})</h2><span>search terms across AI, Python, ML and systems</span></div><input class="search-input" data-glossary-search placeholder="Search: MVCC, coroutine, IoU, KV cache, outbox…" aria-label="Search glossary"><div class="glossary-grid" id="glossary-grid">${glossary.map(g=>`<article class="glossary-item" data-glossary-item="${esc((g.term+' '+g.definition).toLowerCase())}"><strong>${esc(g.term)}</strong><p>${esc(g.definition)}</p></article>`).join('')}</div></section>${(D.cheatsheets||[]).map(c=>`<section class="card" style="margin-bottom:12px"><h2 style="font-size:17px">${esc(c.title)}</h2>${c.bullets?`<ol>${c.bullets.map(x=>`<li class="muted" style="font-size:12px;margin:6px 0">${esc(x)}</li>`).join('')}</ol>`:''}${c.rows?`<div style="overflow:auto"><table class="matrix"><thead><tr>${c.columns.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${c.rows.map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:''}</section>`).join('')}`;}
function sourceHref(s){if(!s.url)return '#';if(s.url.startsWith('local:')){const file=s.url.slice(6);const map={'vision-relay-study.md':'reference/vision-relay-study.md','py-vision-anpr-study.md':'reference/py-vision-anpr-study.md','vms-mqtt-events-study.md':'reference/vms-mqtt-events-study.md','govms-study.md':'reference/govms-study.md','face-recognition-dnn-study.md':'reference/face-recognition-dnn-study.md','resume':'reference/personal-experience.md','application-history':'reference/personal-experience.md','priority-role-brief':'reference/priority-role-brief.md'};return map[file]||'#';}if(s.url.startsWith('gmail:'))return '#';return s.url;}
function renderSources(){const groups=[...new Set(D.sources.map(s=>s.group))];return `${pageHead('Provenance & settings','Sources / Settings','Personal project claims come from your supplied architecture notes, resume/work context and selected GitHub evidence. General concepts are separated into official documentation and learning-science references.')}
<div class="grid two"><section class="card"><h2 style="font-size:17px">Study settings</h2><div class="settings-row"><div><strong>Review mode</strong><div class="tiny muted">Sprint uses shorter intervals; long-term builds durable retention</div></div><select id="setting-mode" data-setting="mode"><option value="sprint" ${state.settings.mode==='sprint'?'selected':''}>Sprint</option><option value="long" ${state.settings.mode==='long'?'selected':''}>Long-term</option></select></div><div class="settings-row"><div><strong>Motion</strong><div class="tiny muted">Animations automatically respect reduced-motion preferences</div></div><input class="switch" type="checkbox" data-setting="motion" ${state.settings.motion?'checked':''}></div><div class="actions"><button class="btn secondary" data-action="export">Export progress JSON</button><button class="btn secondary" data-action="import-toggle">Import</button><button class="btn danger" data-action="reset">Reset</button></div><div class="import-box" id="import-box"><textarea class="self-explain" id="import-json" placeholder="Paste exported JSON"></textarea><button class="btn primary" data-action="import">Restore backup</button></div></section>
<section class="card"><h2 style="font-size:17px">Why this app makes you retrieve</h2><div class="callout"><strong>Testing effect:</strong> delayed retention is stronger after retrieval practice than repeated rereading.</div><div class="callout green" style="margin-top:8px"><strong>Spacing:</strong> distributed practice generally beats massed practice for durable memory.</div><div class="callout amber" style="margin-top:8px"><strong>Desirable difficulty:</strong> feeling slightly harder during study can be a feature, not a bug. Confidence is collected before reveal to expose fluency illusions.</div></section></div>
${groups.map(g=>`<section class="card" style="margin-top:12px"><div class="section-title"><h2>${esc(g)}</h2><span>${D.sources.filter(s=>s.group===g).length} sources</span></div>${D.sources.filter(s=>s.group===g).map(s=>`<div class="source-item"><a href="${esc(sourceHref(s))}" ${/^https?:/.test(s.url)?'target="_blank" rel="noopener"':''}><strong>${esc(s.title)}</strong></a><p>${esc(s.note)}</p></div>`).join('')}</section>`).join('')}`;}

function renderScreen(route){switch(route.page){case'dashboard':return renderDashboard();case'roadmap':return renderRoadmap();case'topic':return renderTopic(route.id);case'labs':return renderLabs();case'review':return renderReview();case'mock':return renderMock();case'projects':return renderProjects();case'cheats':return renderCheats();case'sources':return renderSources();default:return renderDashboard();}}

function navHTML(mobile){return NAV.map(([id,icon,label])=>`<a class="nav-link" data-nav="${id}" href="#/${id}"><span class="nav-icon">${icon}</span><span>${mobile?label.slice(0,7):label}</span></a>`).join('');}
function updateNav(route){if(typeof document==='undefined')return;document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===route.page));const title=document.getElementById('route-title'),kick=document.getElementById('route-kicker');if(title)title.textContent=route.page==='topic'?(topicBy(route.id)||{}).title||'Topic':(NAV.find(x=>x[0]===route.page)||['','','Dashboard'])[2];if(kick)kick.textContent=route.page==='topic'?domainBy((topicBy(route.id)||{}).domain).title:'ENGINEERING ATLAS';}
function render(){if(typeof document==='undefined')return;const r=parseRoute(location.hash);const app=document.getElementById('app');if(app)app.innerHTML=renderScreen(r);updateNav(r);updateProgressBadge();document.body.classList.toggle('motion-off',state.settings.motion===false);if(r.page==='mock')tickMock();}
function toast(msg){if(typeof document==='undefined')return;const e=document.getElementById('toast');if(!e)return;e.textContent=msg;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1600);}
function tickMock(){if(typeof document==='undefined'||!ui.mockStart)return;const el=document.getElementById('mock-timer');if(!el)return;const sec=Math.floor((Date.now()-ui.mockStart)/1000);el.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;clearTimeout(tickMock.t);tickMock.t=setTimeout(tickMock,500);}
function updateTopicCardMastery(topicId){const cs=Object.values(state.cards).filter(c=>c.topicId===topicId);if(!cs.length)return;const score={again:.1,hard:.45,good:.8,easy:1};tstate(topicId).cards=cs.reduce((s,c)=>s+(score[c.lastRating]||0),0)/cs.length;}
function rerender(){render();}

function handleAction(btn){const a=btn.dataset.action;if(!a)return;
 if(a==='toggle-sidebar'){document.body.classList.toggle('sidebar-open');return;}
 if(a==='quick-review'){location.hash='#/review';return;}
 if(a==='toggle-mode'){state.settings.mode=state.settings.mode==='sprint'?'long':'sprint';save();render();toast(`Review mode: ${state.settings.mode}`);return;}
 if(a==='reveal-lesson'){const id=btn.dataset.topic,el=document.getElementById('lesson-answer-'+id);if(el)el.classList.add('revealed');tstate(id).lesson=Math.max(tstate(id).lesson,.5);tstate(id).lastStudied=Date.now();save();return;}
 if(a==='complete-topic'){const id=btn.dataset.topic;tstate(id).lesson=1;tstate(id).lastStudied=Date.now();save();toast('Lesson marked studied');render();return;}
 if(a==='save-explanation'){const id=btn.dataset.topic,el=document.getElementById('self-'+id);state.notes['topic:'+id]=el?el.value:'';tstate(id).explanation=(el&&el.value.trim().length>=80)?1:.6;tstate(id).lastStudied=Date.now();save();toast('Explanation saved');render();return;}
 if(a==='answer-quiz'){const id=btn.dataset.topic,t=topicBy(id),q=t.quiz[0],idx=Number(btn.dataset.index);document.querySelectorAll(`[data-action="answer-quiz"][data-topic="${id}"]`).forEach((x,i)=>{x.classList.remove('correct','wrong');if(i===q.answer)x.classList.add('correct');else if(i===idx)x.classList.add('wrong')});const fb=document.getElementById('quiz-feedback-'+id);if(fb)fb.innerHTML=`<div class="callout ${idx===q.answer?'green':'red'}" style="margin-top:8px">${idx===q.answer?'Correct.':'Not quite.'} ${esc(q.why)}</div>`;tstate(id).quiz=idx===q.answer?1:Math.max(tstate(id).quiz,.2);tstate(id).lastStudied=Date.now();save();return;}
 if(a==='lab-tab'){ui.activeLab=btn.dataset.lab;render();return;}
 if(a==='toggle-failure'){const el=document.getElementById(btn.dataset.target);if(el)el.classList.toggle('revealed');return;}
 if(a==='confidence'){ui.confidence=Number(btn.dataset.value);render();return;}
 if(a==='reveal-card'){ui.reviewRevealed=true;render();return;}
 if(a==='rate-card'){const id=btn.dataset.card,c=state.cards[id];if(c&&Sch){state.cards[id]=Sch.rateCard(c,btn.dataset.rating,Date.now(),state.settings.mode);updateTopicCardMastery(c.topicId);tstate(c.topicId).lastStudied=Date.now();save();ui.reviewIndex++;ui.reviewRevealed=false;ui.confidence=0;render();}return;}
 if(a==='mock-mode'){ui.mockMode=btn.dataset.mode;ui.mockIndex=0;ui.mockRevealed=false;ui.mockStart=0;render();return;}
 if(a==='mock-start'){ui.mockStart=Date.now();tickMock();return;}
 if(a==='mock-reveal'){ui.mockRevealed=true;render();return;}
 if(a==='mock-next'){ui.mockIndex++;ui.mockRevealed=false;ui.mockStart=0;render();return;}
 if(a==='mock-score'){const pool=mockPool(),q=pool[ui.mockIndex];state.mock.history.push({at:Date.now(),type:ui.mockMode,question:q.q,score:Number(btn.dataset.score),seconds:ui.mockStart?Math.round((Date.now()-ui.mockStart)/1000):null});save();toast('Mock score saved');ui.mockIndex++;ui.mockRevealed=false;ui.mockStart=0;render();return;}
 if(a==='export'){const text=Store.exportState();try{const blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='engineering-learning-os-progress.json';link.click();URL.revokeObjectURL(url);}catch(e){navigator.clipboard&&navigator.clipboard.writeText(text);toast('Backup copied');}return;}
 if(a==='import-toggle'){const el=document.getElementById('import-box');if(el)el.style.display=el.style.display==='block'?'none':'block';return;}
 if(a==='import'){try{state=Store.importState(document.getElementById('import-json').value);prepareCards();toast('Progress restored');render();}catch(e){toast('Invalid backup JSON');}return;}
 if(a==='reset'){if(!window.confirm||window.confirm('Reset all study progress?')){state=Store.reset();prepareCards();toast('Progress reset');render();}return;}
}
function updateLabInput(el){const L=ui.activeLab;const map={messaging:'msg',scale:'scale',db:'db',harness:'harness',rag:'rag',inference:'inf',python:'async',cosine:'cosine',yolo:'yolo',capacity:'capacity'};const key=map[L];if(!key)return;ui[key]=ui[key]||{};let v=el.type==='checkbox'?el.checked:el.value;if(el.type==='range')v=Number(v);ui[key][el.dataset.labInput]=v;render();}
function handleSetting(el){const k=el.dataset.setting;if(!k)return;const v=el.type==='checkbox'?el.checked:el.value;state.settings[k]=v;save();render();}
function keydown(e){if(parseRoute(location.hash).page!=='review')return;if(e.code==='Space'){e.preventDefault();ui.reviewRevealed=true;render();}if(ui.reviewRevealed&&['1','2','3','4'].includes(e.key)){const r=['again','hard','good','easy'][Number(e.key)-1];const deck=reviewDeck(),c=deck[ui.reviewIndex%deck.length];if(c){state.cards[c.id]=Sch.rateCard(state.cards[c.id],r,Date.now(),state.settings.mode);updateTopicCardMastery(c.topicId);save();ui.reviewIndex++;ui.reviewRevealed=false;ui.confidence=0;render();}}}
function init(){if(typeof document==='undefined')return;const dn=document.getElementById('desktop-nav'),mn=document.getElementById('mobile-nav');if(dn)dn.innerHTML=navHTML(false);if(mn)mn.innerHTML=navHTML(true);document.addEventListener('click',e=>{const b=e.target.closest&&e.target.closest('[data-action]');if(b)handleAction(b);const nav=e.target.closest&&e.target.closest('.nav-link');if(nav)document.body.classList.remove('sidebar-open');});document.addEventListener('input',e=>{if(e.target&&e.target.dataset.labInput)updateLabInput(e.target);if(e.target&&e.target.hasAttribute&&e.target.hasAttribute('data-glossary-search')){const q=e.target.value.trim().toLowerCase();document.querySelectorAll('[data-glossary-item]').forEach(x=>{x.hidden=!!q&&!x.dataset.glossaryItem.includes(q);});}if(e.target&&e.target.hasAttribute&&e.target.hasAttribute('data-topic-search')){const q=e.target.value.trim().toLowerCase();document.querySelectorAll('[data-topic-search-item]').forEach(x=>{x.hidden=!!q&&!x.dataset.topicSearchItem.includes(q);});}});document.addEventListener('change',e=>{if(e.target&&e.target.dataset.setting)handleSetting(e.target);if(e.target&&e.target.dataset.labInput&&e.target.tagName==='SELECT')updateLabInput(e.target);});document.addEventListener('keydown',keydown);window.addEventListener('hashchange',render);if(!location.hash)location.hash='#/dashboard';render();state.stats.sessions=(state.stats.sessions||0)+1;state.stats.lastOpen=Date.now();save();const mode=document.getElementById('study-mode');if(mode)mode.textContent=state.settings.mode==='sprint'?'Sprint mode':'Long-term';}

window.InterviewApp={parseRoute,renderScreen,renderDashboard,renderRoadmap,renderTopic,renderLabs,renderReview,renderMock,renderProjects,renderCheats,renderSources,renderLab,reviewDeck,handleAction};
if(typeof document!=='undefined'&&document.addEventListener)document.addEventListener('DOMContentLoaded',init);
})();
