#!/usr/bin/env node
'use strict';
// Generates docs/VISUAL_AUDIT.md — per-lesson visual status.
import fs from 'node:fs';

const window = {};
for (const f of ['js/data.js', 'js/expanded-data.js']) {
  new Function('window', fs.readFileSync(f, 'utf8'))(window);
}
const D = window.InterviewOSData;
new Function('window', fs.readFileSync('js/diagrams.js', 'utf8'))(window);
const Diag = window.InterviewDiagrams;

// Ratchet list shared with tests/visual-semantics.test.js
const APPROVED = new Set(['python-coroutines-tasks','python-event-loop','python-taskgroup','python-cancellation-timeouts','async-semaphore-queue']);

const rows = [];
for (const t of D.topics) {
  let status, detail;
  if (APPROVED.has(t.id)) { status = 'APPROVED'; detail = `${t.visuals.length} purpose-built visuals`; }
  else if (t.visuals && t.visuals.length) { status = 'CUSTOM'; detail = `${t.visuals.length} visual spec(s) — review pending`; }
  else if (t.diagram && Diag.has(t.diagram)) { status = 'GENERIC-REGISTRY'; detail = `named renderer "${t.diagram}" — semantic fit unreviewed`; }
  else { status = 'MISSING'; detail = t.diagram ? `references unregistered "${t.diagram}" (renders nothing)` : 'no visual specified'; }
  rows.push({ id: t.id, title: t.title, priority: t.priority, diagram: t.diagram || '-', status, detail });
}

const counts = rows.reduce((a, r) => ((a[r.status] = (a[r.status] || 0) + 1), a), {});
const line = r => `| ${r.id} | ${r.title.replace(/\|/g, '/')} | P${r.priority} | ${r.diagram} | ${r.status} | ${r.detail} |`;

const md = `# Visual Audit

Generated by \`node tools/visual-audit.mjs\`. Do not hand-edit the table; regenerate.

Statuses: **APPROVED** (passed purpose + semantic review) · **CUSTOM** (explicit visuals,
review pending) · **GENERIC-REGISTRY** (named shared renderer; allowed only where the
renderer genuinely teaches this lesson) · **MISSING** (no visual renders).

Rule: a lesson must never silently receive an unrelated fallback diagram. Unknown
diagram keys render nothing and appear here as MISSING.

## Summary

| Status | Lessons |
|--------|---------|
${Object.entries(counts).map(([k, v]) => `| ${k} | ${v} |`).join('\n')}
| **Total** | ${rows.length} |

## Per-lesson status

| Lesson | Title | Pri | diagram key | Status | Notes |
|--------|-------|-----|-------------|--------|-------|
${rows.map(line).join('\n')}
`;
fs.writeFileSync('docs/VISUAL_AUDIT.md', md);
console.log(`docs/VISUAL_AUDIT.md written — ${rows.length} lessons`);
for (const [k, v] of Object.entries(counts)) console.log(`  ${k}: ${v}`);
