#!/usr/bin/env node
'use strict';
// Generates docs/VISUAL_AUDIT.md — per-lesson visual status.
import fs from 'node:fs';

const window = {};
for (const f of ['js/data.js', 'js/expanded-data.js']) {
  new Function('window', fs.readFileSync(f, 'utf8'))(window);
}
const D = window.InterviewOSData;
new Function('window', fs.readFileSync('js/diagrams.js', 'utf8'))(window);
const Diag = window.InterviewDiagrams;

// Ratchet list shared with tests/visual-semantics.test.js
const APPROVED = new Set(['agent-runtime','harness-optimization','runtime-orchestration','tool-calling','model-routing','memory-systems','rag-grounding','evals-guardrails','ai-observability','local-llm','gpu-fundamentals','triton-optimization','k8s-ai-scaling','backpressure','latency-throughput','fastapi-async','event-driven','reliability-patterns','load-balancing','horizontal-scaling','redis-zset','redis-streams','rabbitmq-deep-dive','kafka-deep-dive','mqtt','broker-decision','postgres-explain','postgres-indexes','sql-joins','db-connection-pooling','db-load-reduction','partitioning','transactions-locks','api-security','multi-tenancy','observability-slos','architecture-tradeoffs','leadership-stories','enterprise-agent-system-design','final-simulation','rag-chunking','prompt-injection','context-engineering','model-caching','queueing-capacity','idempotency','cache-patterns','read-replicas','microservices-boundaries','api-rate-limits','docker-cicd','voice-ai','vector-search','system-design-process','cost-optimization','fine-tuning-vs-rag','data-pipelines','object-storage','python-object-model','python-mutable-immutable','python-copying','python-closures-decorators','python-iterators-generators','python-context-managers','python-exceptions','python-typing-dataclasses','python-oop-solid','python-gil','python-threading','python-multiprocessing','python-event-loop','python-coroutines-tasks','python-taskgroup','python-cancellation-timeouts','async-semaphore-queue','async-db-pools','fastapi-lifecycle','python-profiling','ml-train-val-test','ml-bias-variance','ml-overfitting-regularization','ml-gradient-descent','ml-loss-functions','ml-metrics','ml-regression-metrics','ml-cross-validation','ml-feature-scaling','ml-data-leakage','ml-class-imbalance','ml-embeddings','cosine-similarity','ml-knn','ml-svm','ml-tree-ensembles','ml-neural-net-basics','ml-cnn-basics','ml-transfer-learning','ml-drift','cv-image-representation','cv-preprocessing','yolo-architecture','yolo-loss','iou-nms','yolo-anchorfree','yolo-training-debug','object-tracking','sort-deepsort','kalman-filter','hungarian','anpr-end-to-end','plate-recognition','temporal-voting','mmc-pipeline','motion-detection','scene-detection','face-recognition-pipeline','arcface','faiss-ann','multimodal-embeddings','vlm-vs-vllm','vllm-serving','video-sampling','video-context-fusion','system-design-requirements','system-design-capacity','system-design-api','load-balancer-algorithms','reverse-proxy','cache-aside-design','consistent-hashing','cdn-design','db-replication-design','sharding-strategies','distributed-locks','leader-election','consensus-basics','cap-pacelc','id-generation','bloom-filter','rate-limiter-design','outbox-pattern','saga-pattern','bulkhead-pattern','four-golden-signals','graceful-degradation','large-file-upload-design','search-system-design','big-o','arrays-hashmaps','stack-queue','linked-list','trees-bst','heap','graphs-bfs-dfs','binary-search','recursion-dp','oop-pillars','design-patterns','testing-pyramid','python-args-kwargs','python-scope-methods','db-normalization-bcnf','sql-window-cte','docker-fundamentals','docker-network-volumes','kubernetes-core','linux-process-memory']);

const rows = [];
for (const t of D.topics) {
  let status, detail;
  if (APPROVED.has(t.id)) { status = 'APPROVED'; detail = `${t.visuals.length} purpose-built visuals`; }
  else if (t.visuals && t.visuals.length) { status = 'CUSTOM'; detail = `${t.visuals.length} visual spec(s) — review pending`; }
  else if (t.diagram && Diag.has(t.diagram)) { status = 'GENERIC-REGISTRY'; detail = `named renderer "${t.diagram}" — semantic fit unreviewed`; }
  else { status = 'MISSING'; detail = t.diagram ? `references unregistered "${t.diagram}" (renders nothing)` : 'no visual specified'; }
  rows.push({ id: t.id, title: t.title, priority: t.priority, diagram: t.diagram || '-', status, detail });
}

const counts = rows.reduce((a, r) => ((a[r.status] = (a[r.status] || 0) + 1), a), {});
const line = r => `| ${r.id} | ${r.title.replace(/\|/g, '/')} | P${r.priority} | ${r.diagram} | ${r.status} | ${r.detail} |`;

const md = `# Visual Audit

Generated by \`node tools/visual-audit.mjs\`. Do not hand-edit the table; regenerate.

Statuses: **APPROVED** (passed purpose + semantic review) · **CUSTOM** (explicit visuals,
review pending) · **GENERIC-REGISTRY** (named shared renderer; allowed only where the
renderer genuinely teaches this lesson) · **MISSING** (no visual renders).

Rule: a lesson must never silently receive an unrelated fallback diagram. Unknown
diagram keys render nothing and appear here as MISSING.

## Summary

| Status | Lessons |
|--------|---------|
${Object.entries(counts).map(([k, v]) => `| ${k} | ${v} |`).join('\n')}
| **Total** | ${rows.length} |

## Per-lesson status

| Lesson | Title | Pri | diagram key | Status | Notes |
|--------|-------|-----|-------------|--------|-------|
${rows.map(line).join('\n')}
`;
fs.writeFileSync('docs/VISUAL_AUDIT.md', md);
console.log(`docs/VISUAL_AUDIT.md written — ${rows.length} lessons`);
for (const [k, v] of Object.entries(counts)) console.log(`  ${k}: ${v}`);
